/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check Db */
        get: operations["health_check_db_health_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Verify Firebase token, get or create the user, and return profile.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create User */
        post: operations["create_user_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_users_me_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai-characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ai Characters */
        get: operations["list_ai_characters_ai_characters_get"];
        put?: never;
        /** Create Ai Character */
        post: operations["create_ai_character_ai_characters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai-characters/{character_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ai Character */
        get: operations["get_ai_character_ai_characters__character_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Practice Sessions */
        get: operations["list_practice_sessions_practice_sessions_get"];
        put?: never;
        /** Create Practice Session */
        post: operations["create_practice_session_practice_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice-sessions/{session_id}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Practice Session Detail */
        get: operations["get_practice_session_detail_practice_sessions__session_id__detail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice-sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Practice Session */
        get: operations["get_practice_session_practice_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice-sessions/{session_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Practice Session Status */
        patch: operations["update_practice_session_status_practice_sessions__session_id__status_patch"];
        trace?: never;
    };
    "/practice-sessions/{session_id}/generate-feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Feedback
         * @description Generate AI feedback for a completed practice session.
         */
        post: operations["generate_feedback_practice_sessions__session_id__generate_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session-participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Session Participants */
        get: operations["list_session_participants_session_participants_get"];
        put?: never;
        /** Create Session Participant */
        post: operations["create_session_participant_session_participants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session-participants/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session Participants Bulk */
        post: operations["create_session_participants_bulk_session_participants_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session-participants/{participant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session Participant */
        get: operations["get_session_participant_session_participants__participant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session-messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Session Messages */
        get: operations["list_session_messages_session_messages_get"];
        put?: never;
        /** Create Session Message */
        post: operations["create_session_message_session_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session-messages/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session Message */
        get: operations["get_session_message_session_messages__message_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session-feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session Feedback By Session */
        get: operations["get_session_feedback_by_session_session_feedback_get"];
        put?: never;
        /** Create Session Feedback */
        post: operations["create_session_feedback_session_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session-feedback/{feedback_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session Feedback */
        get: operations["get_session_feedback_session_feedback__feedback_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Feedback Metrics */
        get: operations["list_feedback_metrics_feedback_metrics_get"];
        put?: never;
        /** Create Feedback Metric */
        post: operations["create_feedback_metric_feedback_metrics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback-metrics/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Feedback Metrics Bulk */
        post: operations["create_feedback_metrics_bulk_feedback_metrics_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback-metrics/{metric_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Feedback Metric */
        get: operations["get_feedback_metric_feedback_metrics__metric_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversation/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Message
         * @description Send a message to the AI and receive a response.
         *
         *     This endpoint processes the user's spoken message, generates an AI response
         *     using the appropriate prompt for the session mode, and optionally returns
         *     synthesized audio using VOICEVOX.
         */
        post: operations["send_message_conversation_message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversation/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Conversation
         * @description Start a conversation and get the AI's opening message.
         *
         *     This endpoint generates the AI's initial greeting or prompt based on
         *     the session mode and settings.
         */
        post: operations["start_conversation_conversation_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversation/message/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Message Stream
         * @description メッセージを送信し、Server-Sent Events経由でストリーミングレスポンスを受信する
         *
         *     このエンドポイントはユーザーのメッセージを処理し、AI応答を
         *     リアルタイムでストリーミング配信します（増分テキストと音声チャンクを含む）
         *
         *     Server-Sent Events (SSE)を返す:
         *     - event: metadata, data: {participant_id, speaker_id}
         *     - event: text_chunk, data: {text}
         *     - event: audio_chunk, data: {audio_base64, sequence, text}
         *     - event: complete, data: {text, audio_sequence_count}
         *     - event: error, data: {message}
         */
        post: operations["send_message_stream_conversation_message_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversation/start/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Conversation Stream
         * @description 会話を開始し、AIの開始メッセージをSSE経由でストリーミング配信する
         *
         *     Server-Sent Events (SSE)を返す:
         *     - event: metadata, data: {participant_id, speaker_id}
         *     - event: text_chunk, data: {text}
         *     - event: audio_chunk, data: {audio_base64, sequence, text}
         *     - event: complete, data: {text, audio_sequence_count}
         *     - event: error, data: {message}
         */
        post: operations["start_conversation_stream_conversation_start_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AiCharacterCreateRequest */
        AiCharacterCreateRequest: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Strictness */
            strictness: string;
            /** Personality */
            personality?: string | null;
            /** Voice Style */
            voice_style?: string | null;
            /** Description */
            description?: string | null;
        };
        /** AiCharacterResponse */
        AiCharacterResponse: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Strictness */
            strictness: string;
            /** Personality */
            personality: string | null;
            /** Voice Style */
            voice_style: string | null;
            /** Description */
            description: string | null;
            /** Is Active */
            is_active: boolean;
        };
        /** ConversationMessageRequest */
        ConversationMessageRequest: {
            /** Session Id */
            session_id: number;
            /** Message */
            message: string;
            /**
             * Generate Audio
             * @default true
             */
            generate_audio: boolean;
        };
        /** ConversationResponse */
        ConversationResponse: {
            /** Text */
            text: string;
            /** Audio Base64 */
            audio_base64?: string | null;
            /** Speaker Id */
            speaker_id?: number | null;
            /** Participant Id */
            participant_id?: number | null;
        };
        /** ConversationStartRequest */
        ConversationStartRequest: {
            /** Session Id */
            session_id: number;
            /**
             * Generate Audio
             * @default true
             */
            generate_audio: boolean;
        };
        /** DashboardResponse */
        DashboardResponse: {
            /** Total Sessions */
            total_sessions: number;
            /** Completed Sessions */
            completed_sessions: number;
            /** Average Score */
            average_score: number | null;
            /** Recent Sessions */
            recent_sessions: components["schemas"]["SessionListItem"][];
        };
        /**
         * FeedbackGenerationResponse
         * @description Response for feedback generation API.
         */
        FeedbackGenerationResponse: {
            /** Session Id */
            session_id: number;
            /** Feedback Id */
            feedback_id: number;
            /** Overall Score */
            overall_score: number;
            /** Summary Title */
            summary_title: string;
            /** Short Comment */
            short_comment: string | null;
        };
        /** FeedbackMetricBulkCreateRequest */
        FeedbackMetricBulkCreateRequest: {
            /** Metrics */
            metrics: components["schemas"]["FeedbackMetricCreateRequest"][];
        };
        /** FeedbackMetricCreateRequest */
        FeedbackMetricCreateRequest: {
            /** Feedback Id */
            feedback_id: number;
            /** Metric Key */
            metric_key: string;
            /** Metric Value */
            metric_value: number | string;
            /** Metric Label */
            metric_label?: string | null;
            /** Metric Unit */
            metric_unit?: string | null;
        };
        /** FeedbackMetricResponse */
        FeedbackMetricResponse: {
            /** Id */
            id: number;
            /** Feedback Id */
            feedback_id: number;
            /** Metric Key */
            metric_key: string;
            /** Metric Value */
            metric_value: string;
            /** Metric Label */
            metric_label: string | null;
            /** Metric Unit */
            metric_unit: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginRequest
         * @description Sent after Firebase client-side auth to register or retrieve the user.
         */
        LoginRequest: {
            /** Display Name */
            display_name?: string | null;
            /** Photo Url */
            photo_url?: string | null;
        };
        /** PaginatedSessionListResponse */
        PaginatedSessionListResponse: {
            /** Items */
            items: components["schemas"]["SessionListItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PracticeSessionCreateRequest */
        PracticeSessionCreateRequest: {
            /** User Id */
            user_id: number;
            /** Mode */
            mode: string;
            /** Participant Count */
            participant_count: number;
            /**
             * Feedback Enabled
             * @default true
             */
            feedback_enabled: boolean;
            /** Theme */
            theme?: string | null;
            /** Presentation Duration Sec */
            presentation_duration_sec?: number | null;
            /** Presentation Qa Count */
            presentation_qa_count?: number | null;
            /** User Goal */
            user_goal?: string | null;
            /** User Concerns */
            user_concerns?: string | null;
            /** Session Brief */
            session_brief?: string | null;
            /** Target Context */
            target_context?: string | null;
        };
        /**
         * PracticeSessionDetailResponse
         * @description Full session detail: session + participants + messages + feedback.
         */
        PracticeSessionDetailResponse: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /** Status */
            status: string;
            /** Mode */
            mode: string;
            /** Participant Count */
            participant_count: number;
            /** Feedback Enabled */
            feedback_enabled: boolean;
            /** Theme */
            theme: string | null;
            /** Overall Score */
            overall_score: number | null;
            /** Feedback Summary */
            feedback_summary: string | null;
            /** Started At */
            started_at: string | null;
            /** Ended At */
            ended_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Participants
             * @default []
             */
            participants: components["schemas"]["SessionParticipantResponse"][];
            /**
             * Messages
             * @default []
             */
            messages: components["schemas"]["SessionMessageResponse"][];
            feedback?: components["schemas"]["SessionFeedbackNested"] | null;
        };
        /** PracticeSessionResponse */
        PracticeSessionResponse: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /** Status */
            status: string;
            /** Mode */
            mode: string;
            /** Participant Count */
            participant_count: number;
            /** Feedback Enabled */
            feedback_enabled: boolean;
            /** Theme */
            theme: string | null;
            /** Presentation Duration Sec */
            presentation_duration_sec: number | null;
            /** Presentation Qa Count */
            presentation_qa_count: number | null;
            /** User Goal */
            user_goal: string | null;
            /** User Concerns */
            user_concerns: string | null;
            /** Session Brief */
            session_brief: string | null;
            /** Target Context */
            target_context: string | null;
            /** Overall Score */
            overall_score: number | null;
            /** Feedback Summary */
            feedback_summary: string | null;
            /** Started At */
            started_at: string | null;
            /** Ended At */
            ended_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PracticeSessionStatusUpdateRequest */
        PracticeSessionStatusUpdateRequest: {
            /** Status */
            status: string;
        };
        /** SessionFeedbackCreateRequest */
        SessionFeedbackCreateRequest: {
            /** Session Id */
            session_id: number;
            /** User Id */
            user_id: number;
            /** Summary Title */
            summary_title: string;
            /** Positive Points */
            positive_points: unknown;
            /** Improvement Points */
            improvement_points: unknown;
            /** Short Comment */
            short_comment?: string | null;
            /** Closing Message */
            closing_message?: string | null;
        };
        /** SessionFeedbackNested */
        SessionFeedbackNested: {
            /** Id */
            id: number;
            /** Summary Title */
            summary_title: string;
            /** Short Comment */
            short_comment: string | null;
            /** Positive Points */
            positive_points: unknown;
            /** Improvement Points */
            improvement_points: unknown;
            /** Closing Message */
            closing_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Metrics
             * @default []
             */
            metrics: components["schemas"]["FeedbackMetricResponse"][];
        };
        /** SessionFeedbackResponse */
        SessionFeedbackResponse: {
            /** Id */
            id: number;
            /** Session Id */
            session_id: number;
            /** User Id */
            user_id: number;
            /** Summary Title */
            summary_title: string;
            /** Short Comment */
            short_comment: string | null;
            /** Positive Points */
            positive_points: unknown;
            /** Improvement Points */
            improvement_points: unknown;
            /** Closing Message */
            closing_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SessionListItem
         * @description Lightweight item for session history list.
         */
        SessionListItem: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /** Mode */
            mode: string;
            /** Theme */
            theme: string | null;
            /** Overall Score */
            overall_score: number | null;
            /** Has Feedback */
            has_feedback: boolean;
            /** Started At */
            started_at: string | null;
            /** Ended At */
            ended_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SessionMessageCreateRequest */
        SessionMessageCreateRequest: {
            /** Session Id */
            session_id: number;
            /** Participant Id */
            participant_id?: number | null;
            /** Sequence No */
            sequence_no: number;
            /** Content */
            content: string;
            /** Transcript Confidence */
            transcript_confidence?: number | string | null;
        };
        /** SessionMessageResponse */
        SessionMessageResponse: {
            /** Id */
            id: number;
            /** Session Id */
            session_id: number;
            /** Participant Id */
            participant_id: number | null;
            /** Sequence No */
            sequence_no: number;
            /** Content */
            content: string;
            /** Transcript Confidence */
            transcript_confidence: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SessionParticipantBulkCreateRequest */
        SessionParticipantBulkCreateRequest: {
            /** Participants */
            participants: components["schemas"]["SessionParticipantCreateRequest"][];
        };
        /** SessionParticipantCreateRequest */
        SessionParticipantCreateRequest: {
            /** Session Id */
            session_id: number;
            /** Ai Character Id */
            ai_character_id: number;
            /** Display Name */
            display_name: string;
            /** Role */
            role: string;
            /** Seat Index */
            seat_index: number;
        };
        /** SessionParticipantResponse */
        SessionParticipantResponse: {
            /** Id */
            id: number;
            /** Session Id */
            session_id: number;
            /** Ai Character Id */
            ai_character_id: number;
            /** Display Name */
            display_name: string;
            /** Role */
            role: string;
            /** Seat Index */
            seat_index: number;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            ai_character?: components["schemas"]["AiCharacterResponse"] | null;
        };
        /** UserCreateRequest */
        UserCreateRequest: {
            /** Firebase Uid */
            firebase_uid: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Display Name */
            display_name: string;
            /** Photo Url */
            photo_url?: string | null;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /** Firebase Uid */
            firebase_uid: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Photo Url */
            photo_url: string | null;
            /** Onboarding Completed */
            onboarding_completed: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_db_health_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    get_dashboard_users_me_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
        };
    };
    list_ai_characters_ai_characters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiCharacterResponse"][];
                };
            };
        };
    };
    create_ai_character_ai_characters_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiCharacterCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiCharacterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ai_character_ai_characters__character_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiCharacterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_practice_sessions_practice_sessions_get: {
        parameters: {
            query: {
                user_id: number;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSessionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_practice_session_practice_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PracticeSessionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_practice_session_detail_practice_sessions__session_id__detail_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_practice_session_practice_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_practice_session_status_practice_sessions__session_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PracticeSessionStatusUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_feedback_practice_sessions__session_id__generate_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackGenerationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_session_participants_session_participants_get: {
        parameters: {
            query: {
                session_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionParticipantResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_participant_session_participants_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionParticipantCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionParticipantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_participants_bulk_session_participants_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionParticipantBulkCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionParticipantResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_participant_session_participants__participant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                participant_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionParticipantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_session_messages_session_messages_get: {
        parameters: {
            query: {
                session_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionMessageResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_message_session_messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionMessageCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_message_session_messages__message_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_feedback_by_session_session_feedback_get: {
        parameters: {
            query: {
                session_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionFeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_feedback_session_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionFeedbackCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionFeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_feedback_session_feedback__feedback_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedback_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionFeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_feedback_metrics_feedback_metrics_get: {
        parameters: {
            query: {
                feedback_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackMetricResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_feedback_metric_feedback_metrics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackMetricCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackMetricResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_feedback_metrics_bulk_feedback_metrics_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackMetricBulkCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackMetricResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feedback_metric_feedback_metrics__metric_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                metric_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackMetricResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_conversation_message_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_conversation_conversation_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_stream_conversation_message_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_conversation_stream_conversation_start_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
