"""create session_feedback table

Revision ID: 7f3996cf3266
Revises: 2cbc9de8bded
Create Date: 2026-03-25 15:09:35.864749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f3996cf3266'
down_revision: Union[str, Sequence[str], None] = '2cbc9de8bded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_feedback',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('summary_title', sa.Text(), nullable=False),
    sa.Column('short_comment', sa.Text(), nullable=True),
    sa.Column('positive_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('improvement_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('closing_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['practice_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_feedback')
    # ### end Alembic commands ###
