"""create feedback_metrics table

Revision ID: af1d032b65fb
Revises: 7f3996cf3266
Create Date: 2026-03-25 15:14:45.845791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af1d032b65fb'
down_revision: Union[str, Sequence[str], None] = '7f3996cf3266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('feedback_id', sa.BigInteger(), nullable=False),
    sa.Column('metric_key', sa.String(length=50), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('metric_label', sa.String(length=100), nullable=True),
    sa.Column('metric_unit', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['session_feedback.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback_metrics')
    # ### end Alembic commands ###
