"""create practice_sessions table

Revision ID: dcacb1f2069d
Revises: 22130acacd9c
Create Date: 2026-03-25 08:21:56.052382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcacb1f2069d'
down_revision: Union[str, Sequence[str], None] = '22130acacd9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='waiting', nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('participant_count', sa.Integer(), nullable=False),
    sa.Column('feedback_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('theme', sa.Text(), nullable=True),
    sa.Column('presentation_duration_sec', sa.Integer(), nullable=True),
    sa.Column('presentation_qa_count', sa.Integer(), nullable=True),
    sa.Column('user_goal', sa.Text(), nullable=True),
    sa.Column('user_concerns', sa.Text(), nullable=True),
    sa.Column('session_brief', sa.Text(), nullable=True),
    sa.Column('target_context', sa.String(length=50), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('feedback_summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("mode IN ('presentation', 'interview', 'free_conversation')", name='ck_practice_sessions_mode'),
    sa.CheckConstraint("status IN ('waiting', 'active', 'completed', 'cancelled', 'error')", name='ck_practice_sessions_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('practice_sessions')
    # ### end Alembic commands ###
